//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.06 at 03:21:41 PM GMT 
//


package manager.reports.report;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the report package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Report_QNAME = new QName("", "Report");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: report
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link FieldType }
     * 
     */
    public FieldType createFieldType() {
        return new FieldType();
    }

    /**
     * Create an instance of {@link EntrySetType }
     * 
     */
    public EntrySetType createEntrySetType() {
        return new EntrySetType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntrySetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Report")
    public JAXBElement<EntrySetType> createReport(EntrySetType value) {
        return new JAXBElement<EntrySetType>(_Report_QNAME, EntrySetType.class, null, value);
    }

}
